### ISSUE TITLE
How to Add Actionbar to Preferences Screen

### ISSUE THREAD

**Issue by sarfraznawaz2005** [sitefinitysteve/nativescript-preferences#2]
### Which platform(s) does your issue occur on?
- Android
- Marshmallow
- Device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.1.0
- Cross-platform modules: 5.0.2
- Runtime(s): 5.0.0
- Plugin(s): 
````
        "nativescript-dev-sass": "~1.6.0",
        "nativescript-dev-webpack": "~0.18.0",
        "eslint": "~5.8.0"
````
### Please, tell us how to recreate the issue in as much detail as possible. 

Thanks for nice plugin!

I have implemented this and works fine. However on preferences screen, actionbar is missing.

Can you please tell how can I add actionbar to preferences screen to make it consistent with rest of the app.

Thanks

**Comment by sarfraznawaz2005** [comment]
Can you at least tell me how I can fix this on my own if you don't plan to fix this? Thanks

**Comment by sitefinitysteve** [comment]
Hey man, it's not that it needs to _be fixed_ it's not there, it would be an enhancement.  I can't commit to any timelines on adding it though. I'm not sure myself, would have to investigate.

PRs accepted though if you can't wait.

**Comment by sarfraznawaz2005** [comment]
Thanks for the reply man !

I would love to make a PR but I am new to this realm of Android. So I will wait and will implement in my apps once it is done.

Thanks again
