### ISSUE TITLE
Empty preference screen on Android

### ISSUE THREAD

**Issue by babbamaic** [sitefinitysteve/nativescript-preferences#5]
I have an issue with opening preference screen on an android device (real device and emulator). It shows an empty activity screen. 
In the console a got:
`JS: topmost() is deprecated. Use Frame.topmost() instead`

- CLI: 6.5.0
- Cross-platform modules: 6.5.1
- Runtime(s): tns-android 6.5.0
- dependencies: {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.3",
    "nativescript-angular": "~8.21.0",
    "nativescript-localize": "^4.2.1",
    "nativescript-nfc": "^4.1.0",
    "nativescript-preferences": "^1.1.2",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  }

**Comment by sitefinitysteve** [comment]
Yeah I see that error, hang tight

**Comment by sitefinitysteve** [comment]
I pushed 1.2, the demo loads so I guess she's good to go?
